import cookieParser from 'cookie-parser';
import express, { Application } from 'express';
import helmet from 'helmet';
import SearchTrackRoute from './routes/SearchTrackRoute';
import RoomsRoute from './routes/RoomsRoute';
import SongsRoute from './routes/SongsRoute';
import CategoriesRoute from './routes/CategoriesRoute';
import DailyRoute from './routes/DailyRoute';
import AudioRoute from './routes/AudioRoute';
import GuildRouter from './routes/GuildRoute';
import ArticlesRoute from './routes/ArticlesRoute';
import ImagesRoute from './routes/ImagesRoute';
import WikisRoute from './routes/WikisRoute';
import QuizesRoute from './routes/QuizesRoute';
import UserRoute from './routes/UserRoute';
import { scheduleSongUpdate } from './utils/ScheduleDailySongChange';
import { morganMiddleware } from './middlewares/morganMiddleware';
import { errorHandlingMiddleware } from './middlewares/errorHandlingMiddleware';
import cors from 'cors';

export const app: Application = express();

app.use(morganMiddleware);
app.use(errorHandlingMiddleware);
app.use(cookieParser());
app.use(cors());
app.use(helmet());
app.use('/externalApi/track/search/', SearchTrackRoute);
app.use('/externalApi/rooms/', RoomsRoute);
app.use('/externalApi/songs/', SongsRoute);
app.use('/externalApi/categories/', CategoriesRoute);
app.use('/externalApi/daily/', DailyRoute);
app.use('/externalApi/audio/', AudioRoute);
app.use('/externalApi/guilds', GuildRouter);
app.use('/externalApi/articles', ArticlesRoute);
app.use('/externalApi/images', ImagesRoute);
app.use('/externalApi/wikis', WikisRoute);
app.use('/externalApi/quizes', QuizesRoute);
app.use('/externalApi/user', UserRoute);
app.use(() => scheduleSongUpdate);
